export default Images
 = [
    {url: require('../assets/1.jpeg')},
    {url: require('../assets/2.jpeg')},
    {url: require('../assets/3.jpeg')},
    {url: require('../assets/4.jpeg')},
    {url: require('../assets/5.jpeg')},
    {url: require('../assets/6.jpeg')},
    {url: require('../assets/7.jpeg')},
    {url: require('../assets/8.jpeg')},
    {url: require('../assets/9.jpeg')},
    {url: require('../assets/10.jpeg')},
    {url: require('../assets/11.jpeg')},
    {url: require('../assets/12.jpeg')},
    {url: require('../assets/13.jpeg')},
    {url: require('../assets/14.jpeg')},
    {url: require('../assets/15.jpeg')},
    {url: require('../assets/16.jpeg')},
    {url: require('../assets/17.jpeg')},
    {url: require('../assets/18.jpeg')},
    {url: require('../assets/19.jpeg')},
    {url: require('../assets/20.jpeg')},
    {url: require('../assets/21.jpeg')},
    {url: require('../assets/22.jpeg')},
    {url: require('../assets/23.jpeg')},
    {url: require('../assets/24.jpeg')},
    {url: require('../assets/25.jpeg')},

]